name: abfahrt_finder
description: "Eine App um die Abfahrten in den nahen Stationen einzusehen."
application_id:

publish_to: 'none'

version: 0.9.0+1

environment:
  sdk: ^3.7.2
  flutter: 3.29.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.3
  http: ^1.3.0
  provider: ^6.1.4
  intl: ^0.20.2
  settings_ui: ^2.0.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.3
  flutter_compass: ^0.8.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/product/bus.png
    - assets/product/sbahn.png
    - assets/product/ubahn.png
    - assets/product/tram.png
    - assets/product/ferry.png
    - assets/product/placeholder.png
