name: abfahrt_finder
description: "Eine App um die Abfahrten in den nahen Stationen einzusehen."
application_id:

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.3
  http: ^1.3.0
  provider: ^6.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/product/bus.png
    - assets/product/sbahn.png
    - assets/product/ubahn.png
    - assets/product/placeholder.png
